{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ba1aa69e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: line-bot-sdk in e:\\anaconda\\lib\\site-packages (3.5.0)\n",
      "Requirement already satisfied: aiohttp==3.8.5 in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (3.8.5)\n",
      "Requirement already satisfied: Deprecated in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (1.2.14)\n",
      "Requirement already satisfied: python-dateutil>=2.5.3 in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (2.8.2)\n",
      "Requirement already satisfied: future in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (0.18.2)\n",
      "Requirement already satisfied: aenum>=3.1.11 in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (3.1.15)\n",
      "Requirement already satisfied: requests==2.31.0 in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (2.31.0)\n",
      "Requirement already satisfied: pydantic<3,>=2.0.3 in e:\\anaconda\\lib\\site-packages (from line-bot-sdk) (2.4.2)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (1.3.3)\n",
      "Requirement already satisfied: charset-normalizer<4.0,>=2.0 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (2.0.4)\n",
      "Requirement already satisfied: attrs>=17.3.0 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (21.4.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (4.0.2)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (6.0.2)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (1.2.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in e:\\anaconda\\lib\\site-packages (from aiohttp==3.8.5->line-bot-sdk) (1.8.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in e:\\anaconda\\lib\\site-packages (from requests==2.31.0->line-bot-sdk) (3.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in e:\\anaconda\\lib\\site-packages (from requests==2.31.0->line-bot-sdk) (1.26.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in e:\\anaconda\\lib\\site-packages (from requests==2.31.0->line-bot-sdk) (2022.12.7)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in e:\\anaconda\\lib\\site-packages (from pydantic<3,>=2.0.3->line-bot-sdk) (4.8.0)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in e:\\anaconda\\lib\\site-packages (from pydantic<3,>=2.0.3->line-bot-sdk) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.10.1 in e:\\anaconda\\lib\\site-packages (from pydantic<3,>=2.0.3->line-bot-sdk) (2.10.1)\n",
      "Requirement already satisfied: six>=1.5 in e:\\anaconda\\lib\\site-packages (from python-dateutil>=2.5.3->line-bot-sdk) (1.16.0)\n",
      "Requirement already satisfied: wrapt<2,>=1.10 in e:\\anaconda\\lib\\site-packages (from Deprecated->line-bot-sdk) (1.14.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -iohttp (e:\\anaconda\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "pip install line-bot-sdk\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ecfdd6b",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [28/Dec/2023 17:15:06] \"POST /callback HTTP/1.1\" 200 -\n",
      "[2023-12-28 17:16:39,796] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'ee6d1f6d-b40d-49af-9871-091453295897', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:16:41 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:16:41 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:16:39] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:16:47,066] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '83f37ec1-48be-4d6e-ba39-f7744733a637', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:16:48 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:16:48 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:16:47] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:16:54,630] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'ba7de3cb-5b3f-40e8-ad67-305493edb045', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:16:56 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:16:56 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [28/Dec/2023 17:16:54] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:16:57,638] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'a3808eb8-8dcd-4f91-95cc-4579228288c5', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:16:59 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:16:59 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:16:57] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:17:02,308] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'ddea6519-2b8b-4e1e-bf94-efabc6944111', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:17:03 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:17:03 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:17:02] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:17:09,701] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '620d4d15-578c-4e3c-a147-a9c43c30d09b', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:17:11 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:17:11 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [28/Dec/2023 17:17:09] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:27:02,963] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '1690ca26-04da-483a-b003-671f82ebe377', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:27:04 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:27:04 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:27:02] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:27:17,627] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'a17765ac-b918-4875-ba4b-2b4a02c5c065', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:27:19 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:27:19 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:27:17] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:27:20,556] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '348e7719-dfb3-4a64-b093-49e2f6f5f79c', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:27:22 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:27:22 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [28/Dec/2023 17:27:20] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:27:22,701] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': 'b8ba927d-1250-48a9-a0c1-98a573a0b3ad', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:27:24 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:27:24 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:27:22] \"POST /callback HTTP/1.1\" 500 -\n",
      "[2023-12-28 17:27:26,634] ERROR in app: Exception on /callback [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 41, in callback\n",
      "    handler.handle(body, signature)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 227, in handle\n",
      "    self.__invoke_func(func, event, payload)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\webhook.py\", line 239, in __invoke_func\n",
      "    func(event)\n",
      "  File \"C:\\Users\\Gary\\AppData\\Local\\Temp\\ipykernel_12160\\1285387881.py\", line 118, in handle_message\n",
      "    line_bot_api.reply_message_with_http_info(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 40, in wrapper_function\n",
      "    return vd.call(*args, **kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 134, in call\n",
      "    return self.execute(m)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\pydantic\\v1\\decorator.py\", line 206, in execute\n",
      "    return self.raw_function(**d, **var_kwargs)\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api\\messaging_api.py\", line 6674, in reply_message_with_http_info\n",
      "    return self.api_client.call_api(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 407, in call_api\n",
      "    return self.__call_api(resource_path, method,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 222, in __call_api\n",
      "    raise e\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 212, in __call_api\n",
      "    response_data = self.request(\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\api_client.py\", line 451, in request\n",
      "    return self.rest_client.post_request(url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 270, in post_request\n",
      "    return self.request(\"POST\", url,\n",
      "  File \"E:\\Anaconda\\lib\\site-packages\\linebot\\v3\\messaging\\rest.py\", line 229, in request\n",
      "    raise ApiException(http_resp=r)\n",
      "linebot.v3.messaging.exceptions.ApiException: (400)\n",
      "Reason: Bad Request\n",
      "HTTP response headers: HTTPHeaderDict({'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '18803725-c188-463a-96d7-09ed8a8edd46', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Thu, 28 Dec 2023 09:27:28 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Thu, 28 Dec 2023 09:27:28 GMT', 'Connection': 'close'})\n",
      "HTTP response body: {\"message\":\"Invalid reply token\"}\n",
      "\n",
      "127.0.0.1 - - [28/Dec/2023 17:27:26] \"POST /callback HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, abort\n",
    "\n",
    "from linebot.v3 import (\n",
    "    WebhookHandler\n",
    ")\n",
    "from linebot.v3.exceptions import (\n",
    "    InvalidSignatureError\n",
    ")\n",
    "from linebot.v3.messaging import (\n",
    "    Configuration,\n",
    "    ApiClient,\n",
    "    MessagingApi,\n",
    "    ReplyMessageRequest,\n",
    "    TextMessage,\n",
    "    QuickReply,\n",
    "    QuickReplyItem,\n",
    "    MessageAction,\n",
    ")\n",
    "from linebot.v3.webhooks import (\n",
    "    MessageEvent,\n",
    "    TextMessageContent\n",
    ")\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "configuration = Configuration(access_token='3cr/+n7t7z7I0qs9rDDSu8i3T1y1LaQ+F6R5pm4l27jE1yUxkLD7z6tY4AtihSYaKa+X2CMPXrhvdcYH5zFvsEzhWXH47A0FHoJjsfI2hbZM2yu2QCuvwEMz+NxnSI9xWYFRnIC2LTcZ8Hff45jEfgdB04t89/1O/w1cDnyilFU=')\n",
    "handler = WebhookHandler('f4949399f3f5584661547ff355573385')\n",
    "\n",
    "\n",
    "@app.route(\"/callback\", methods=['POST'])\n",
    "def callback():\n",
    "    # get X-Line-Signature header value\n",
    "    signature = request.headers['X-Line-Signature']\n",
    "\n",
    "    # get request body as text\n",
    "    body = request.get_data(as_text=True)\n",
    "    app.logger.info(\"Request body: \" + body)\n",
    "\n",
    "    # handle webhook body\n",
    "    try:\n",
    "        handler.handle(body, signature)\n",
    "    except InvalidSignatureError:\n",
    "        app.logger.info(\"Invalid signature. Please check your channel access token/channel secret.\")\n",
    "        abort(400)\n",
    "\n",
    "    return 'OK'\n",
    "\n",
    "\n",
    "@handler.add(MessageEvent, message=TextMessageContent)\n",
    "def handle_message(event):\n",
    "    mtext = event.message.text\n",
    "    with ApiClient(configuration) as api_client:\n",
    "        line_bot_api = MessagingApi(api_client)\n",
    "        if mtext == \"@自我介紹\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"教師您好，我是教師規章機器人，能為您提供便捷的規章資訊。\")])\n",
    "            ) \n",
    "        elif mtext == \"@規章選單\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(\n",
    "                                text=\"請選擇您欲了解的規章條例\",\n",
    "                                quick_reply = QuickReply(\n",
    "                                items=[\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"新聘教師教學經費補助辦法\", text=\"新聘教師教學經費補助辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"教師請假補課調課代課規定\",text=\"教師請假補課調課代課規定\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"優良教研人員教勵辦法\", text=\"優良教研人員教勵辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"新聘傑出教研人員獎勵辦法\", text=\"新聘傑出教研人員獎勵辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"新進或年輕傑出教研人員學術研究補助辦法\", text=\"新進或年輕傑出教研人員學術研究補助辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"羅家倫校長年輕傑出研究獎設置辦法\", text=\"羅家倫校長年輕傑出研究獎設置辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"人社領域教學優良教師研究補助辦法\", text=\"人社領域教學優良教師研究補助辦法\")),\n",
    "                                    QuickReplyItem(action=MessageAction(label=\"教研人員教學、研究、輔導及服務獎勵辦法\", text=\"教研人員教學、研究、輔導及服務獎勵辦法\")),\n",
    "                                ]))])\n",
    "            )\n",
    "        elif mtext == \"@快速鏈接\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"若您覺得我說得不夠詳細，我這邊為您整理了所有規章的鏈接:\\\n",
    "                                                                                        \\n\\n新聘教師教學經費補助辦法:https://reurl.cc/rraVkO \\\n",
    "                                                                                        \\n\\n教師請假補課調課代課規定: https://reurl.cc/aL5Dz3 \\\n",
    "                                                                                        \\n\\n優良教研人員教勵辦法: https://reurl.cc/G4dYlG \\\n",
    "                                                                                        \\n\\n新聘傑出教研人員獎勵辦法: https://reurl.cc/g48orb \\\n",
    "                                                                                        \\n\\n新進或年輕傑出教研人員學術研究補助辦法: https://reurl.cc/prmRVQ \\\n",
    "                                                                                        \\n\\n羅家倫校長年輕傑出研究獎設置辦法: https://reurl.cc/E42v0a \\\n",
    "                                                                                        \\n\\n人社領域教學優良教師研究補助辦法: https://reurl.cc/G4dY03 \\\n",
    "                                                                                        \\n\\n教研人員教學、研究、輔導及服務獎勵辦法: https://reurl.cc/54oN6y\")])\n",
    "            )\n",
    "        elif mtext == \"新聘教師教學經費補助辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"申請人限為本校服務未滿(含)三年之新進教師，最高額度十萬元，申請者應檢具計畫書與填具申請表於每年教務處公告期間提出申請。每人補助一次為限。\")])\n",
    "            )\n",
    "        elif mtext == \"教師請假補課調課代課規定\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"教師請假未能事先安排補課、調課者，請於銷假後一週內，由任課老師與學生商定 補課時間，並知會開課單位。\")])\n",
    "            )\n",
    "        elif mtext == \"優良教研人員教勵辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"本獎勵每人每年以2 千元為原則。 適用對象：本校專任（案）教研人員、助教、教官，在教學、研究、輔 導及服務有貢獻者。 含帶職帶薪休假研究、講學、進修及育嬰留職停薪 之教研人員，不含博士後研究員、除育嬰外留職停薪之教研人員。\")])\n",
    "            )\n",
    "        elif mtext == \"新聘傑出教研人員獎勵辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"獎勵對象為本校國內第一次聘任之新進專任教研人員。於到職日起三年內得申請本獎勵。獎金以每月一萬元至二萬元為原則，獎勵期間以一年為限，獎金原則逐月領取。\")])\n",
    "            )\n",
    "        elif mtext == \"新進或年輕傑出教研人員學術研究補助辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"1.新進教研人員研究相關補助至多20萬元。\\n2.年輕傑出教研人員相關補助至多50-100萬。(暫停補助)\\n3.補助經費執行期限次年度1月起至12月止。\")])\n",
    "            )\n",
    "        elif mtext == \"羅家倫校長年輕傑出研究獎設置辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"獎勵方式: \\n1.獲獎人數每年以2至4人為原則。 \\n2.每人獎金60萬元，按月發給，為期一年。 \\n3.獲獎人以獲頒一次獎項為限。\")])\n",
    "            )\n",
    "        elif mtext == \"人社領域教學優良教師研究補助辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"對象為文學院、管理學院、客家學院及人社相關領域之助理教授級以上專任（專案）教師，每案補助設備費及其他費用以十五萬元為原則，本辦法補助以三次為限，得於五年內提出申請。\")])\n",
    "            )\n",
    "        elif mtext == \"教研人員教學、研究、輔導及服務獎勵辦法\":\n",
    "            line_bot_api.reply_message_with_http_info(\n",
    "                ReplyMessageRequest(reply_token=event.reply_token,messages=[TextMessage(text=\"獎金支領人數核給比例：\\n1.講座教授：以不超過全校專任(案)教研人員之6%為原則。\\n2.特聘教授：以不超過全校專任(案)教研人員之11%為原則。\\n3.研究傑出獎：以不超過全校專任(案)教研人員之19%為原則。\\n4.新聘傑出教研人員獎勵：以不超過全校專任(案)教研人員之4% 為原則。\")])\n",
    "            )\n",
    "        line_bot_api.reply_message_with_http_info(\n",
    "            ReplyMessageRequest(\n",
    "                reply_token=event.reply_token,\n",
    "                messages=[TextMessage(text=event.message.text)]\n",
    "            )\n",
    "        )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fc797b6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
